# Generated by Django 6.0.5 on 2026-05-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerpageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registers',
        ),
    ]
